version: "3.5"

services:

  jenkins:
    restart: unless-stopped
    build:
      context: configs/jenkins
    user: root
    ports:
    - 2245:8080
    - 2246:50000
    volumes:
    - ./jenkins_home:/var/jenkins_home
    - ./configs/ssh:/root/.ssh
    - /var/run/docker.sock:/var/run/docker.sock
